Study
Macdeal/html_css-_Tutorial pull request #1
Opened 2022-09-02 04:31 UTC by Macdeal

please review this

2022-09-02 07:17 UTC, donjude-eng requested changes

2022-09-02 07:17 UTC, donjude-eng commented on tut4-css/index.html
> +
can remove empty space?

2022-09-02 07:17 UTC, donjude-eng commented on tut5-css/selector.html
> +        <h1><strong>THE GREAT INDIAN FESTIVAL </strong></h1>
always good to split to

```
<header> - Defines a header for a document or a section
<nav> - Defines a set of navigation links
<section> - Defines a section in a document
<footer> - Defines a footer for a document or a section
```

2022-09-02 07:17 UTC, donjude-eng commented on tut6-10/index.html
> +
remove this line

2022-09-02 09:43 UTC, Macdeal commented on tut5-css/selector.html
> +        <h1><strong>THE GREAT INDIAN FESTIVAL </strong></h1>
ok

2022-09-02 09:43 UTC, Macdeal commented on tut6-10/index.html
> +
yes

2022-09-02 09:45 UTC, Macdeal commented on tut4-css/index.html
> +
yes i will do

2022-09-05 08:42 UTC, donjude-eng approved these changes

2022-09-05 10:10 UTC, merged